/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2019-12-16 21:05:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import com.sun.org.apache.xerces.internal.impl.dv.dtd.NMTOKENDatatypeValidator;
import java.sql.*;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("com.sun.org.apache.xerces.internal.impl.dv.dtd.NMTOKENDatatypeValidator");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Hantube</title>\r\n");
      out.write("<style>\r\n");
      out.write("\thtml, body {\r\n");
      out.write("\t\t\tmargin:0;\r\n");
      out.write("\t\t\theight:100%;\r\n");
      out.write("\t\t\toverflow: hidden;\r\n");
      out.write("\t\t\tfont-family:\"나눔고딕\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\timg {\r\n");
      out.write("\t\t\tmax-width:100%; max-height:100%;\r\n");
      out.write("            vertical-align:middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.maintab {\r\n");
      out.write("\t\t\t\twidth:100%; height:60px; background:#ffffff;\r\n");
      out.write("\t\t\t\tbox-shadow: 0px 2px 4px 0px #ced6e1;\r\n");
      out.write("\t\t\t\tmargin-bottom:2px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menutab {\r\n");
      out.write("\t\t\t\tborder-right:2px solid #c9cbce;\r\n");
      out.write("\t\t\t\twidth:240px; height:100%;\r\n");
      out.write("\t\t\t\tbackground:#ffffff;\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menucontents {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth:100%; height:40px;\r\n");
      out.write("\t\t\t\tline-height:40px;\r\n");
      out.write("\t\t\t\tvertical-align:middle;\r\n");
      out.write("\t\t\t\tcolor:#474747;\r\n");
      out.write("\t\t\t\tfont-weight:normal;\r\n");
      out.write("\t\t\t\tfont-size:21px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menucontents:hover {\r\n");
      out.write("\t\t\t\tbackground-color:#e5e5e5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menucontents-icon {\r\n");
      out.write("\t\t\t\twidth:30px; height:40px;\r\n");
      out.write("\t\t\t\tmargin-left:20px;\r\n");
      out.write("\t\t\t\tmargin-right:20px;\r\n");
      out.write("\t\t\t\tfloat:left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.contentstab1 {\r\n");
      out.write("\t\t\t\twidth:100%; height:auto;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.contentstab2 {\r\n");
      out.write("\t\t\t\twidth:100%; height:500px;\r\n");
      out.write("\t\t\t\tbackground:#ffffff;\r\n");
      out.write("\t\t\t\tbox-shadow: 0px 2px 0px 0px #ced6e1;\r\n");
      out.write("\t\t\t\tmargin-bottom:2px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.contentstag {\r\n");
      out.write("\t\t\t\tdisplay: inline-block;\r\n");
      out.write("\t\t\t\twidth:50%;\r\n");
      out.write("\t\t\t\tpadding-top: 20px; padding-bottom:20px; text-align:left;\r\n");
      out.write("\t\t\t\tfont-size: 22px;\r\n");
      out.write("\t\t\t\tcolor: #595959;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.contentstypebox {\r\n");
      out.write("\t\t\t\tdisplay: inline-block;\r\n");
      out.write("\t\t\t\twidth:50%; height:50px;\r\n");
      out.write("\t\t\t\ttext-align:left;\r\n");
      out.write("\t\t\t\tbackground:white;\r\n");
      out.write("\t\t\t\tborder:1px solid #c9cbce;\r\n");
      out.write("\t\t\t\tborder-radius:3px;\r\n");
      out.write("\t\t\t\tfont-size: 18px;\r\n");
      out.write("\t\t\t\tcolor: #595959;\r\n");
      out.write("\t\t\t\tmargin-bottom: 20px;\r\n");
      out.write("\t\t\t\tline-height: 50px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.videobox {\r\n");
      out.write("\t\t\t\twidth:50%; height: 100%;\r\n");
      out.write("\t\t\t\tborder:1px solid #c9cbce;\r\n");
      out.write("\t\t\t\tborder-radius:3px;\r\n");
      out.write("\t\t\t\tbackground: white;\r\n");
      out.write("\t\t\t\tmargin: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.contentsproduct {\r\n");
      out.write("\t\t\t\twidth:270px; height: 410px;\r\n");
      out.write("\t\t\t\tbackground:white;\r\n");
      out.write("\t\t\t\tmargin-left: 15px; margin-right: 15px;\r\n");
      out.write("\t\t\t\tdisplay: inline-block;\r\n");
      out.write("\t\t\t\tborder: 1px solid #c9cbce;\r\n");
      out.write("\t\t\t\tborder-radius: 3px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.logobox {\r\n");
      out.write("\t\t\t\twidth:240px; height:100%;\r\n");
      out.write("\t\t\t\tcolor:skyblue;\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tinput::-webkit-input-placeholder { text-align:right; }\r\n");
      out.write("\tinput::-moz-placeholder { text-align:right; }\r\n");
      out.write("\tinput:-ms-input-placeholder { text-align:right; }\r\n");
      out.write("\tinput:-moz-placeholder { text-align:right; }\r\n");
      out.write("\tinput::placeholder { text-align:right; }\r\n");
      out.write("\t\r\n");
      out.write("\t.searchbox {\r\n");
      out.write("\t\t\t\twidth:400px; height:100%;\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.accountbox {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth:220px; height:100%;\r\n");
      out.write("\t\t\t\tline-height:60px;x\r\n");
      out.write("\t\t\t\tvertical-align:middle;\r\n");
      out.write("\t\t\t\tfloat: right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.accountmenubox {\r\n");
      out.write("\t\t\t\twidth:320px; height:100%;\r\n");
      out.write("\t\t\t\tfloat: right;\r\n");
      out.write("\t\t\t\tline-height:60px;\r\n");
      out.write("\t\t\t\tvertical-align:middle;\r\n");
      out.write("\t\t\t\ttext-align:center;\r\n");
      out.write("\t\t\t\tfont-size: 14pt;\r\n");
      out.write("\t\t\t\tcolor: #434343;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.accountmenucontents {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth:80px; height: 100%;\r\n");
      out.write("\t\t\t\tfloat: right; vertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.accountmenucontents:hover {\r\n");
      out.write("\t\t\t\tcolor: #4c8fff;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.logocontents {\r\n");
      out.write("\t\t\t\tpadding-left: 20px; padding-top: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.searchcontents {\r\n");
      out.write("\t\t\t\tposition:relative;\r\n");
      out.write("\t\t\t\ttop:10px;\r\n");
      out.write("\t\t\t\twidth:340px; height:35px;\r\n");
      out.write("\t\t\t\tborder:1px solid #0068ff;\t\r\n");
      out.write("\t\t\t\tborder-radius:45px;\r\n");
      out.write("\t\t\t\tline-height: 35px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput:focus { outline: none;  }\r\n");
      out.write("\t\r\n");
      out.write("\t.accountcontents {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth:100px; height:42px;\r\n");
      out.write("\t\t\t\tline-height: 42px;\r\n");
      out.write("\t\t\t\tborder:1.3px solid #095bb7;\r\n");
      out.write("\t\t\t\tcolor:#0046af;\r\n");
      out.write("\t\t\t\tborder-radius:3px;\r\n");
      out.write("\t\t\t\tmargin-left: 10px;\r\n");
      out.write("\t\t\t\tmargin-right: 40px;\r\n");
      out.write("\t\t\t\tmargin-top: 6px;\r\n");
      out.write("\t\t\t\tbackground-color:white;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t\t\t\tfont-size:18px;\r\n");
      out.write("\t\t\t\tfloat:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.accountcontents img {\r\n");
      out.write("\t\t\t\tdisplay: inline;\r\n");
      out.write("\t}\r\n");
      out.write("\t.accountcontents img.over {\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.accountcontents:hover img {\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.accountcontents:hover img.over {\r\n");
      out.write("\t\t\t\tdisplay: inline;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.accountcontents:hover {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth:100px; height:42px;\r\n");
      out.write("\t\t\t\tline-height: 42px;\r\n");
      out.write("\t\t\t\tborder:1px solid #095bb7;\r\n");
      out.write("\t\t\t\tcolor:#ffffff;\r\n");
      out.write("\t\t\t\tborder-radius:3px;\r\n");
      out.write("\t\t\t\tmargin-left: 10px;\r\n");
      out.write("\t\t\t\tmargin-right: 40px;\r\n");
      out.write("\t\t\t\tmargin-top: 6px;\r\n");
      out.write("\t\t\t\tbackground-color:#095bb7;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t\t\t\tfont-size:18px;\r\n");
      out.write("\t\t\t\tfloat:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.videocontents {\r\n");
      out.write("\t\t\t\twidth: 100%; float: left;\r\n");
      out.write("\t\t\t\theight:100%;\r\n");
      out.write("\t\t\t\tborder: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.videotitle {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px;\r\n");
      out.write("\t\t\t\tfont-size:17px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.videocomment {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px;\r\n");
      out.write("\t\t\t\tfont-size:15px;\r\n");
      out.write("\t\t\t\tcolor:#525252;\r\n");
      out.write("\t\t\t\tmargin-top:3px;\r\n");
      out.write("\t\t\t\tmargin-bottom: 7px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.videodate {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 20px;\r\n");
      out.write("\t\t\t\tline-height:20px;\r\n");
      out.write("\t\t\t\tfont-size:14px;\r\n");
      out.write("\t\t\t\tcolor:#767676;\r\n");
      out.write("\t\t\t\tvertical-align:middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.videouser {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px;\r\n");
      out.write("\t\t\t\tfont-size:15px;\r\n");
      out.write("\t\t\t\tcolor:black;\r\n");
      out.write("\t\t\t\tline-height:50px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.totalvideo {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth:100%; height:180px; margin-top:20px;\r\n");
      out.write("\t\t\t\tmargin-bottom: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.totalvideo:hover {\r\n");
      out.write("\t\t\t\twidth:100%; height:180px; margin-top:20px;\r\n");
      out.write("\t\t\t\tmargin-bottom: 20px;\r\n");
      out.write("\t\t\t\tbackground:#e5e5e5;\r\n");
      out.write("\t}\r\n");
      out.write("\t.accountdropmenubox {\r\n");
      out.write("\t\t\t\twidth: 160px; height: 100px; background: white;\r\n");
      out.write("\t\t\t\tposition: absolute; text-align:center;\r\n");
      out.write("\t\t\t\tborder:1px solid #c9cbce;\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t\t\t\tfont-size:18px;\r\n");
      out.write("\t\t\t\tcolor: #595959;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenureplace {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tline-height: 50px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenureplace:hover {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tbackground: #e5e5e5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenulogout {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tline-height: 50px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenulogout:hover {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tbackground: #e5e5e5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.insertdropmenubox {\r\n");
      out.write("\t\t\t\twidth: 160px; height: 150px; background: white;\r\n");
      out.write("\t\t\t\tposition: absolute; text-align:center;\r\n");
      out.write("\t\t\t\tborder:1px solid #c9cbce;\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t\t\t\tfont-size:18px;\r\n");
      out.write("\t\t\t\tcolor: #595959;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenuvideo {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tline-height: 50px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenuvideo:hover {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tbackground: #e5e5e5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenureview {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tline-height: 50px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenureview:hover {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tbackground: #e5e5e5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenupost {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tline-height: 50px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenupost:hover {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tbackground: #e5e5e5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.videocntbox {\r\n");
      out.write("\t\t\t\ttext-align: right;float: right; padding-right: 20px;\r\n");
      out.write("\t\t\t\tfont-size:14px;\r\n");
      out.write("\t\t\t\tcolor:#767676;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.videouserimg {\r\n");
      out.write("\t\t\t\tmargin-top:8px;\r\n");
      out.write("\t\t\t\tfloat:left; width: 30px; height: 30px; border-radius: 50%; border:1.9px solid #cfd1d4;\r\n");
      out.write("\t\t\t\tbackground-repeat: no-repeat; background-size: 30px 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.sorttypebox {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 100px; height: 100%; float: left;\r\n");
      out.write("\t\t\t\tfont-size:15px;\r\n");
      out.write("\t\t\t\tcolor:#767676;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.sorttypebox:hover {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 100px; height: 100%; float: left;\r\n");
      out.write("\t\t\t\tfont-size:15px;\r\n");
      out.write("\t\t\t\tcolor:#767676;\r\n");
      out.write("\t\t\t\tbackground: #e5e5e5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction accountdropmenu() {\r\n");
      out.write("\t\tif(document.getElementById('account_checkdropmenustate').value == 1){\r\n");
      out.write("\t\t\t$(\".accountdropmenubox\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\tdocument.getElementById('account_checkdropmenustate').value = 2;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\".accountdropmenubox\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\tdocument.getElementById('account_checkdropmenustate').value = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction insertdropmenu() {\r\n");
      out.write("\t\tif(document.getElementById('insert_checkdropmenustate').value == 1){\r\n");
      out.write("\t\t\t$(\".insertdropmenubox\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\tdocument.getElementById('insert_checkdropmenustate').value = 2;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\".insertdropmenubox\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\tdocument.getElementById('insert_checkdropmenustate').value = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String sorttype = request.getParameter("sort");
	if(sorttype == null){
		sorttype = "1";
	}
	int sortcnt = Integer.parseInt(sorttype);
	
	String sortNew = "";
	String sortView = "";
	
	if(sortcnt == 1){
		sortNew = "style='border-bottom:2px solid #3363ff; color:#3363ff;'";
	}
	
	if(sortcnt == 2){
		sortView = "style='border-bottom:2px solid #3363ff; color:#3363ff;'";
	}

      out.write("\r\n");
      out.write("\r\n");

	String idv = request.getParameter("hidden_name");
	if(idv != null){
		session.setAttribute("id_login", idv);
	}
	String id_login = (String)session.getAttribute("id_login");

	String login_nick = "";
	String login_img = "";

	String login_state_yes = "display:none;";
	String login_state_no = "display:none;";

      out.write('\r');
      out.write('\n');

Connection conn=null;
PreparedStatement pstmt = null;
ResultSet rs = null;


try{
	String driverName = "com.mysql.cj.jdbc.Driver";
	String jdbcUrl = "jdbc:mysql://localhost:3306/han_db?serverTimezone=Asia/Seoul";
	String dbId="guestid2019";
	String dbPass="guestpwd2019";
	
	Class.forName("com.mysql.cj.jdbc.Driver");
	conn = DriverManager.getConnection(jdbcUrl, dbId, dbPass);

	if(id_login != null){
		String sql = "select * from account_db where user_id = '" + id_login + "'";
		pstmt = conn.prepareStatement(sql);
		rs = pstmt.executeQuery();
		if(rs.next()){
			login_nick = rs.getString("user_nick");
			login_img = rs.getString("user_img");
		}
		
	}
	
}catch(Exception e){
	e.printStackTrace();
}finally{
	if(conn != null)
		try{conn.close();}catch(SQLException sqle){}
	if(pstmt != null)
		try{conn.close();}catch(SQLException sqle){}
	if(rs != null)
		try{conn.close();}catch(SQLException sqle){}
}

      out.write('\r');
      out.write('\n');

	if(id_login != null){
		login_state_yes = "display:block;";
		login_state_no = "display:none;";
	}else{
		login_state_yes = "display:none;";
		login_state_no = "display:block;";
	}


      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"maintab\">\r\n");
      out.write("\t<div class=\"logobox\">\r\n");
      out.write("\t\t<div class=\"logocontents\">\r\n");
      out.write("\t\t\t<img src=\"resources/imgs/hantv.png\" OnClick=\"location.href='main.jsp'\" style=\"cursor:pointer;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"searchbox\">\r\n");
      out.write("\t\t<div class=\"searchcontents\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-left:10px;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><img src=\"resources/imgs/search_btn.png\"></a>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"검색\" style=\"width:290px; border:none;\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"accountbox\" style=\"");
      out.print(login_state_no);
      out.write("\">\r\n");
      out.write("\t\t<div class=\"accountcontents\" OnClick=\"location.href='login.jsp'\">\r\n");
      out.write("\t\t\t<div style=\"margin-left:10px;\">\r\n");
      out.write("\t\t\t\t로그인\r\n");
      out.write("\t\t\t\t<img src=\"resources/imgs/login_btn.png\">\r\n");
      out.write("\t\t\t\t<img src=\"resources/imgs/login_btn_rollover.png\" class=\"over\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"accountbox\" style=\"");
      out.print(login_state_yes);
      out.write("\" onclick=\"accountdropmenu();\">\r\n");
      out.write("\t\t<div style=\"border-left:1px solid #dcdddf; width:100px; height:100%; padding-left:20px; float: left; text-align: right;\">\r\n");
      out.write("\t\t\t");
      out.print(login_nick );
      out.write("\r\n");
      out.write("\t\t\t<div class=\"accountdropmenubox\">\r\n");
      out.write("\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"account_checkdropmenustate\" value=\"1\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropmenureplace\" OnClick=\"location.href='#'\">\r\n");
      out.write("\t\t\t\t\t\t계정수정\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropmenulogout\" OnClick=\"location.href='logout.jsp'\">\r\n");
      out.write("\t\t\t\t\t\t로그아웃\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"width:40px; height:40px; margin-right:40px; float: right;\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(login_img);
      out.write("\" style=\"width:40px; height:40px;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"accountmenubox\" style=\"");
      out.print(login_state_yes);
      out.write("\">\r\n");
      out.write("\t\t<div class=\"accountmenucontents\" style=\"margin-left: 10px; margin-right: 20px;\">\r\n");
      out.write("\t\t내채널\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"accountmenucontents\" style=\"margin-right: 10px;\" onclick=\"insertdropmenu();\">\r\n");
      out.write("\t\t올리기\r\n");
      out.write("\t\t\t<div class=\"insertdropmenubox\">\r\n");
      out.write("\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"insert_checkdropmenustate\" value=\"1\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropmenuvideo\" OnClick=\"location.href='uploadvideo.jsp'\">\r\n");
      out.write("\t\t\t\t\t\t동영상\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropmenureview\" OnClick=\"location.href='review.jsp'\">\r\n");
      out.write("\t\t\t\t\t\t동영상 리뷰\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropmenupost\" OnClick=\"location.href='uploadpost.jsp'\">\r\n");
      out.write("\t\t\t\t\t\t게시글\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"menutab\">\r\n");
      out.write("\t<div style=\"width:100%; height:10px;\">\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"menucontents\" OnClick=\"location.href='main.jsp'\">\r\n");
      out.write("\t\t<div class=\"menucontents-icon\">\r\n");
      out.write("\t\t\t<img src=\"resources/imgs/home_normal.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"float:left;\">\r\n");
      out.write("\t\t\t홈\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"menucontents\" OnClick=\"location.href='video.jsp'\">\r\n");
      out.write("\t\t<div class=\"menucontents-icon\">\r\n");
      out.write("\t\t\t<img src=\"resources/imgs/hot_normal.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"float:left;\">\r\n");
      out.write("\t\t\t동영상\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"menucontents\" OnClick=\"location.href='review.jsp'\">\r\n");
      out.write("\t\t<div class=\"menucontents-icon\">\r\n");
      out.write("\t\t\t<img src=\"resources/imgs/review_normal.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"float:left;\">\r\n");
      out.write("\t\t\t동영상 리뷰\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"menucontents\" OnClick=\"location.href='board.jsp'\">\r\n");
      out.write("\t\t<div class=\"menucontents-icon\">\r\n");
      out.write("\t\t\t<img src=\"resources/imgs/text_selected.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"color: #4c8fff; float:left;\">\r\n");
      out.write("\t\t\t게시글\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");

conn = null;
pstmt = null;
rs = null;
int numPage = 4;
double pageBlock = 3;
double totalRecord = 0;
double totalPage = 0;
double totalBlock = 0;
String Pagecnt = request.getParameter("Page");
double Page = 0;
int first = 0;
int block = 0;
double firstPage = 0;
double lastPage = 0;
double articleNum = 0;
double articleResult = 0;


Timestamp nowdate = new Timestamp(System.currentTimeMillis());


try{
	String driverName = "com.mysql.cj.jdbc.Driver";
	String jdbcUrl = "jdbc:mysql://localhost:3306/han_db?serverTimezone=Asia/Seoul";
	String dbId="guestid2019";
	String dbPass="guestpwd2019";
	
	Class.forName("com.mysql.cj.jdbc.Driver");
	conn = DriverManager.getConnection(jdbcUrl, dbId, dbPass);

	if(id_login != null){
		String sql = "select * from account_db where user_id = '" + id_login + "'";
		pstmt = conn.prepareStatement(sql);
		rs = pstmt.executeQuery();
		if(rs.next()){
			login_nick = rs.getString("user_nick");
			login_img = rs.getString("user_img");
		}
		
	}
	
	String sql = "select count(cid) from post_db";
	pstmt = conn.prepareStatement(sql);	// 쿼리문 수행할 객체 생성
	rs = pstmt.executeQuery();
	
	if(rs.next()){
		totalRecord = rs.getInt("count(cid)");
		totalPage = Math.ceil(totalRecord/numPage);
		totalBlock = Math.ceil(totalPage/pageBlock);
	}else{
		totalRecord = 0;
		out.print("페이지가 없습니다.");
	}
	
	if(Pagecnt != null){
		Page = Integer.parseInt(Pagecnt);
	}else{
		Page = 1;
	}
	
	first = numPage*(int)(Page-1);
	block = (int)Math.ceil(Page/pageBlock);
	firstPage = (block-1)*pageBlock;
	lastPage = block*pageBlock;
	
	if(block >= totalBlock){
		lastPage = totalPage;
	}
	
	articleNum = totalRecord - numPage*(Page-1);
	if(sortcnt == 1){
		sql = "select * from post_db ORDER BY signdate desc, cid desc LIMIT "+first+", "+numPage;
	}else{
		sql = "select * from post_db ORDER BY viewcnt desc, cid desc LIMIT "+first+", "+numPage;
	}
	pstmt = conn.prepareStatement(sql);
	rs = pstmt.executeQuery();
	
      out.write("\r\n");
      out.write("<div style=\"overflow: auto; width:100%-240px; height:100%; background: #f2f4f7;\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"contentstab1\">\r\n");
      out.write("\t\t\t<div class=\"contentstag\">\r\n");
      out.write("\t\t\t\t게시글\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"contentstypebox\">\r\n");
      out.write("\t\t\t\t<div class=\"sorttypebox\" ");
      out.print(sortNew );
      out.write(" OnClick=\"location.href='board.jsp?sort=1'\">\r\n");
      out.write("\t\t\t\t\t최신순\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"sorttypebox\" ");
      out.print(sortView );
      out.write(" OnClick=\"location.href='board.jsp?sort=2'\">\r\n");
      out.write("\t\t\t\t\t조회순\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"videobox\">\r\n");
      out.write("\t\t\t\t");

					while(rs.next()){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"totalvideo\" OnClick=\"location.href='post.jsp?post=");
      out.print(rs.getString("cid"));
      out.write("'\">\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:98%; height: 100%;text-align: left; margin-left: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"videotitle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(rs.getString("ptitle") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"videocomment\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(rs.getString("comment") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"videodate\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									SimpleDateFormat sdf = new SimpleDateFormat("yyyy. MM. dd");
									String videoDate = sdf.format(rs.getTimestamp("signdate"));
									out.println(videoDate);
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"videouser\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"videouserimg\" style=\"background-image: url('");
      out.print(rs.getString("userimgsrc"));
      out.write("');\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 10px; float: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print( rs.getString("usernick"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"videocntbox\">조회수 ");
      out.print(rs.getInt("viewcnt") );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");

						articleNum--;
					}
				
      out.write("\r\n");
      out.write("\r\n");

}catch(Exception e){
	e.printStackTrace();
}finally{
	if(conn != null)
		try{conn.close();}catch(SQLException sqle){}
	if(pstmt != null)
		try{conn.close();}catch(SQLException sqle){}
	if(rs != null)
		try{conn.close();}catch(SQLException sqle){}
}

      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"width:50%; height: 200px; margin: auto; text-align: center; line-height:100px; vertical-align: middle;\">\r\n");
      out.write("\t\t");

		double myPage = 0;
		int directPage = 0;
			if(block > 1){
				myPage = firstPage;
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"board.jsp?Page=");
      out.print(myPage);
      out.write("&&sort=");
      out.print(sortcnt);
      out.write("\">[이전]</a>\r\n");
      out.write("\t\t\t\t");

			}else{
				out.println("[이전]");
			}
			for(directPage = (int)firstPage+1;directPage<=lastPage;directPage++){
				if(Page == directPage){
					out.print("["+directPage+"]");
				}else{
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"board.jsp?Page=");
      out.print(directPage);
      out.write("&&sort=");
      out.print(sortcnt);
      out.write('"');
      out.write('>');
      out.write('[');
      out.print(directPage);
      out.write("]</a>\r\n");
      out.write("\t\t\t\t\t");

				}
			}
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

			if(block < totalBlock){
				myPage = lastPage+1;
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"board.jsp?Page=");
      out.print(myPage);
      out.write("&&sort=");
      out.print(sortcnt);
      out.write("\">[다음]</a>\r\n");
      out.write("\t\t\t\t");

			}else{
				out.print("[다음]");
			}
		
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
