/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2019-12-12 09:42:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class createaccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>account</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("\thtml, body {\r\n");
      out.write("\t\t\tdisplay: flex;\r\n");
      out.write(" \t\t\talign-items: center;\r\n");
      out.write(" \t\t\tjustify-content: center;\r\n");
      out.write("\t\t\tmargin:0;\r\n");
      out.write("\t\t\theight:100%;\r\n");
      out.write("\t\t\toverflow: auto;\r\n");
      out.write("\t\t\tfont-family:\"나눔고딕\";\r\n");
      out.write("\t\t\tline-height:100%;\r\n");
      out.write("\t\t\tvertical-align:middle;\r\n");
      out.write("\t\t\tbackground:#f2f4f7;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttable {\r\n");
      out.write("\t\t\tpadding: 0px;\r\n");
      out.write("\t\t\tborder: 0px;\r\n");
      out.write("\t\t\tmargin: 0px;\r\n");
      out.write("\t\t\tborder-spacing: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.createbox {\r\n");
      out.write("\t\t\t\twidth:510px; height:430px;\r\n");
      out.write("\t\t\t\tpadding:30px;\r\n");
      out.write("\t\t\t\tborder:1px solid #0068ff;\r\n");
      out.write("\t\t\t\tborder-radius:10px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t\t\t\tbackground:#ffffff;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.create_text {\r\n");
      out.write("\t\t\t\tpadding-left:10px;\r\n");
      out.write("\t\t\t\tborder: 1px solid #dadce0;\r\n");
      out.write("\t\t\t\tborder-radius: 3px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.create_btn {\r\n");
      out.write("\t\t\t\tmargin-top:20px;\r\n");
      out.write("\t\t\t\twidth:100px; height:40px;\r\n");
      out.write("\t\t\t\tbackground-color:#0068ff;\r\n");
      out.write("\t\t\t\tborder:0px;\r\n");
      out.write("\t\t\t\tborder-radius: 2px;\r\n");
      out.write("\t\t\t\tcolor:white;\r\n");
      out.write("\t\t\t\tfloat:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.create_imgchange {\r\n");
      out.write("\t\t\t\twidth:40px; height:25px;\r\n");
      out.write("\t\t\t\tbackground-color:#ffffff;\r\n");
      out.write("\t\t\t\tcolor:#0068ff;\r\n");
      out.write("\t\t\t\tborder:1px solid #0068ff;;\r\n");
      out.write("\t\t\t\tborder-radius: 2px;\r\n");
      out.write("\t\t\t\tfloat:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.create_imgbox {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\ttext-align:center;\r\n");
      out.write("\t\t\t\tmargin-left:20px;\r\n");
      out.write("\t\t\t\tmargin-top:0px;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\twidth:100%-40px; height:100px;\r\n");
      out.write("\t\t\t\tborder: 1px solid #dadce0;\r\n");
      out.write("\t\t\t\tborder-radius: 2px;\r\n");
      out.write("\t\t\t\tline-height: 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.create_id_check {\r\n");
      out.write("\t\t\t\tcolor:red;\r\n");
      out.write("\t\t\t\tfont-size:11px;\r\n");
      out.write("\t\t\t\theight:10px;\r\n");
      out.write("\t\t\t\tborder:0px;\r\n");
      out.write("\t\t\t\twidth:200px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.create_pwd_check {\r\n");
      out.write("\t\t\t\tcolor:red;\r\n");
      out.write("\t\t\t\tfont-size:11px;\r\n");
      out.write("\t\t\t\theight:10px;\r\n");
      out.write("\t\t\t\tborder:0px;\r\n");
      out.write("\t\t\t\twidth:200px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.create_id_check:focus {\r\n");
      out.write("\t\t\t\toutline:none;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.create_pwd_check:focus {\r\n");
      out.write("\t\t\t\toutline:none;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write(" <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction checkimg(){\r\n");
      out.write("\t\talert(\"test\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('#input_id').blur(function(){\r\n");
      out.write("\t\t\tif(document.getElementById('input_id').value != \"\"){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\turl:\"./idcheck.jsp\",\r\n");
      out.write("\t\t\tdata:{\"idc\":$('#input_id').val()},\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tif($.trim(data) == \"YES\"){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('id_check').value = \"이미 사용하는 아이디 입니다.\";\r\n");
      out.write("\t\t\t\t\t$(\".create_id_check\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('id_check').value = \"사용 가능한 아이디 입니다.\";\r\n");
      out.write("\t\t\t\t\t$(\".create_id_check\").css(\"color\", \"green\");\r\n");
      out.write("\t\t\t\t\tif(document.getElementById('create_nick_id').value == \"\"){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('example_id').value = document.getElementById('input_id').value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t}else if(document.getElementById('input_id').value == \"\" && document.getElementById('id_check').value == \"이미 사용하는 아이디 입니다.\" || document.getElementById('id_check').value == \"사용 가능한 아이디 입니다.\"){\r\n");
      out.write("\t\t\t\tdocument.getElementById('id_check').value = \"\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('#create_pwd_check').blur(function(){\r\n");
      out.write("\t\t\tif(document.getElementById('create_pwd_id').value != \"\"){\r\n");
      out.write("\t\t\t\tif(document.getElementById('create_pwd_id').value == document.getElementById('create_pwd_check').value){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('pwd_check_text').value = \"비밀번호가 일치합니다.\";\r\n");
      out.write("\t\t\t\t\t$(\".create_pwd_check\").css(\"color\", \"green\");\r\n");
      out.write("\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('pwd_check_text').value = \"비밀번호가 일치하지 않습니다.\";\r\n");
      out.write("\t\t\t\t\t$(\".create_pwd_check\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tdocument.getElementById('pwd_check_text').value = \"비밀번호를 입력하세요.\";\r\n");
      out.write("\t\t\t\t$(\".create_pwd_check\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\t$(\"#create_pwd_id\").focus();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('#create_pwd_id').blur(function(){\r\n");
      out.write("\t\t\tif(document.getElementById('create_pwd_id').value != \"\"){\r\n");
      out.write("\t\t\t\tif(document.getElementById('create_pwd_id').value == document.getElementById('create_pwd_check').value){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('pwd_check_text').value = \"비밀번호가 일치합니다.\";\r\n");
      out.write("\t\t\t\t\t$(\".create_pwd_check\").css(\"color\", \"green\");\r\n");
      out.write("\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('pwd_check_text').value = \"비밀번호가 일치하지 않습니다.\";\r\n");
      out.write("\t\t\t\t\t$(\".create_pwd_check\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tdocument.getElementById('pwd_check_text').value = \"비밀번호를 입력하세요.\";\r\n");
      out.write("\t\t\t\t$(\".create_pwd_check\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction create_check(){\r\n");
      out.write("\t\tif(document.getElementById('id_check').value == \"사용 가능한 아이디 입니다.\"){\r\n");
      out.write("\t\t\tif(document.getElementById('pwd_check_text').value == \"비밀번호가 일치합니다.\"){\r\n");
      out.write("\t\t\t\tif(document.getElementById('create_name_id').value != \"\"){\r\n");
      out.write("\t\t\t\t\tif(document.getElementById('create_nick_id').value == \"\"){\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('create_nick_id').value = document.getElementById('input_id').value;\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('c_action').submit();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('c_action').submit();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#create_name_id\").focus();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#create_pwd_id\").focus();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#input_id\").focus();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("function nick_example(){\r\n");
      out.write("\tif(document.getElementById('create_nick_id').value == \"\"){\r\n");
      out.write("\t\tif(document.getElementById('input_id').value == \"\"){\r\n");
      out.write("\t\t\tdocument.getElementById('example_id').value = \"example\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tdocument.getElementById('example_id').value = document.getElementById('input_id').value;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tdocument.getElementById('example_id').value = document.getElementById('create_nick_id').value;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"createbox\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<h2>회원가입</h2>\r\n");
      out.write("\t\t계정\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"margin-top:20px;\">\r\n");
      out.write("\r\n");
      out.write("\t");

	String imgsrc = "resources/imgs/account_person.png";
	
      out.write("\r\n");
      out.write("<form action=\"createaction.jsp\" method=\"POST\" id=\"c_action\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"create_id\" id=\"input_id\" placeholder=\"아이디 account\" class=\"create_text\" style=\"width:240px; height:30px;\"></td>\r\n");
      out.write("\t\t\t\t<td rowspan=\"5\" style=\"width:248px; display: table-cell; vertical-align: top;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"create_imgbox\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display:inline-block; width:80px; height:80px; border: 1px solid #dadce0; vertical-align: middle;\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"");
      out.print(imgsrc);
      out.write("\" style=\"width:100%; height:100%;\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"create_check\" onClick=\"checkimg();\" type=\"button\" value=\"변경\" class=\"create_imgchange\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id=\"id_check\" class=\"create_id_check\" style=\"margin-bottom: 20px\" readonly=\"readonly\" tabindex=\"-1\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"create_pwd\" id=\"create_pwd_id\" placeholder=\"비밀번호 password\" class=\"create_text\" style=\"width:240px; height:30px;\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr style=\"height:10px\">\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" id=\"create_pwd_check\" placeholder=\"비밀번호 확인\" class=\"create_text\" style=\"width:240px; height:30px;\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id=\"pwd_check_text\" class=\"create_pwd_check\" readonly=\"readonly\" tabindex=\"-1\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr style=\"height:10px\">\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"create_name\" id=\"create_name_id\" placeholder=\"이름 name\" class=\"create_text\" style=\"width:240px; height:30px;\"></td>\r\n");
      out.write("\t\t\t\t<td rowspan=\"3\" style=\"margin-left:20px;\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-left:20px;\">\r\n");
      out.write("\t\t\t\t미리보기\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"margin-left:40px; margin-top: 20px\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(imgsrc);
      out.write("\" style=\"width:20px; height:20px;\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"example_id\" value=\"example\" style=\"border:0px;\" readonly=\"readonly\" tabindex=\"-1\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr style=\"height:10px\">\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"create_nick\" id=\"create_nick_id\" onkeyup=\"nick_example();\" placeholder=\"닉네임 nickname\" class=\"create_text\" style=\"width:240px; height:30px;\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<input type=\"hidden\" value=\"");
      out.print(imgsrc);
      out.write("\" name=\"create_img\">\r\n");
      out.write("</form>\r\n");
      out.write("\t\t<input type=\"button\" onclick=\"create_check();\" value=\"제출\" class=\"create_btn\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
