/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2019-12-04 14:00:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>HanTube</title>\r\n");
      out.write("<style>\r\n");
      out.write("\thtml, body {\r\n");
      out.write("\t\t\tdisplay: flex;\r\n");
      out.write(" \t\t\talign-items: center;\r\n");
      out.write(" \t\t\tjustify-content: center;\r\n");
      out.write("\t\t\tmargin:0;\r\n");
      out.write("\t\t\theight:100%;\r\n");
      out.write("\t\t\toverflow: auto;\r\n");
      out.write("\t\t\tfont-family:\"나눔고딕\";\r\n");
      out.write("\t\t\tline-height:100%;\r\n");
      out.write("\t\t\tvertical-align:middle;\r\n");
      out.write("\t\t\tbackground:#f2f4f7;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttable {\r\n");
      out.write("\t\t\tpadding: 0px;\r\n");
      out.write("\t\t\tborder: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ta:link { color:#858585; }\r\n");
      out.write("\ta:visited { color:#858585; }\r\n");
      out.write("\ta:hover { color:#0068ff; }\r\n");
      out.write("\ta:active { color:blue; }\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t.loginbox {\r\n");
      out.write("\t\t\t\twidth:420px; height:500px;\r\n");
      out.write("\t\t\t\tborder:1px solid #0068ff;\r\n");
      out.write("\t\t\t\tborder-radius:10px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t\t\t\tbackground:#ffffff;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.logincontents {\r\n");
      out.write("\t\t\t\twidth:100%-120px; height:100%-100px;\r\n");
      out.write("\t\t\t\tmargin-left:60px; margin-right:60px;\r\n");
      out.write("\t\t\t\tmargin-top:50px; margin-bottom:50px;\r\n");
      out.write("\t\t\t\ttext-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.login_id_text {\r\n");
      out.write("\t\t\t\twidth:290px; height:50px;\r\n");
      out.write("\t\t\t\tpadding-left:10px;\r\n");
      out.write("\t\t\t\tborder: 1px solid #dadce0;\r\n");
      out.write("\t\t\t\tborder-radius: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.login_pwd_text {\r\n");
      out.write("\t\t\t\twidth:290px; height:50px;\r\n");
      out.write("\t\t\t\tpadding-left:10px;\r\n");
      out.write("\t\t\t\tborder: 1px solid #dadce0;\r\n");
      out.write("\t\t\t\tborder-radius: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.login_btn {\r\n");
      out.write("\t\t\t\twidth:100px; height:40px;\r\n");
      out.write("\t\t\t\tbackground-color:#0068ff;\r\n");
      out.write("\t\t\t\tborder:0px;\r\n");
      out.write("\t\t\t\tborder-radius: 2px;\r\n");
      out.write("\t\t\t\tcolor:white;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.login_id_check {\r\n");
      out.write("\t\t\t\t width:290px;\r\n");
      out.write("\t\t\t\t color:red;\r\n");
      out.write("\t\t\t\t font-size:11px;\r\n");
      out.write("\t\t\t\t border:0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.login_pwd_check {\r\n");
      out.write("\t\t\t\t width:290px;\r\n");
      out.write("\t\t\t\t color:red;\r\n");
      out.write("\t\t\t\t font-size:11px;\r\n");
      out.write("\t\t\t\t border:0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.login_id_check:focus {\r\n");
      out.write("\t\t\t\toutline: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.login_pwd_check:focus {\r\n");
      out.write("\t\t\t\toutline: none;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");

	String id_login = (String)session.getAttribute("id_login");
	if(id_login != null){
		response.sendRedirect("main.jsp");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction login_check(){\r\n");
      out.write("\t\tif(document.getElementById('login_id').value == \"\"){\r\n");
      out.write("\t\t\tdocument.getElementById('login_check_id').value = \"아이디를 입력하세요.\";\r\n");
      out.write("\t\t\t$(\"#login_id\").focus();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.getElementById('login_password').value == \"\" && document.getElementById('login_check_id').value != \"완료\"){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\turl:\"./idcheck.jsp\",\r\n");
      out.write("\t\tdata:{\"idc\":$('#login_id').val()},\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tif($.trim(data) == \"YES\"){\r\n");
      out.write("\t\t\t\tdocument.getElementById('login_check_id').value = \"완료\";\r\n");
      out.write("\t\t\t\tdocument.getElementById('login_id').setAttribute(\"readonly\", \"readonly\");\r\n");
      out.write("\t\t\t\t$(\".login_id_text\").css(\"border\", \"1px solid #dadce0;\");\r\n");
      out.write("\t\t\t\t$(\".login_id_check\").css(\"color\", \"green\");\r\n");
      out.write("\t\t\t\t$(\".login_id_check\").css(\"text-align\", \"right\");\r\n");
      out.write("\t\t\t\t$(\".help_id\").css(\"visibility\", \"hidden\");\r\n");
      out.write("\t\t\t\t$(\".div_pwd_form\").css(\"visibility\", \"visible\");\r\n");
      out.write("\t\t\t\t$(\"#login_password\").focus();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tdocument.getElementById('login_check_id').value = \"등록되지 않은 사용자입니다.\";\r\n");
      out.write("\t\t\t\t$(\"#login_id\").focus();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t}else if(document.getElementById('login_check_id').value == \"완료\" && document.getElementById('login_password').value != \"\"){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\turl:\"./pwdcheck.jsp\",\r\n");
      out.write("\t\t\tdata:{\"idc\":$('#login_id').val()},\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tif($.trim(data) == \"NO\"){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('login_check_pwd').value = \"비밀번호가 일치하지 않습니다.\";\r\n");
      out.write("\t\t\t\t\t$(\"#login_password\").focus();\r\n");
      out.write("\t\t\t\t}else if($.trim(data) == document.getElementById('login_password').value){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('hidden_id').value = document.getElementById('login_id').value;\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('l_action_id').submit();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('login_check_pwd').value = \"비밀번호가 일치하지 않습니다.\";\r\n");
      out.write("\t\t\t\t\t$(\"#login_password\").focus();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tdocument.getElementById('login_check_pwd').value = \"비밀번호를 입력하세요.\";\r\n");
      out.write("\t\t\t$(\"#login_password\").focus();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String giveid = request.getParameter("id");
	if(giveid == null)
	giveid = "";

      out.write("\r\n");
      out.write("<div class=\"loginbox\">\r\n");
      out.write("\t<div class=\"logincontents\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t<h2>로그인</h2>\r\n");
      out.write("\t\tLOGIN\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"margin-top:30px;\">\r\n");
      out.write("\t\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"login_id\" placeholder=\"아이디 account\" class=\"login_id_text\" value=");
      out.print(giveid );
      out.write("></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr id=\"not_account\" style=\"text-align:left;\">\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" value=\"\" id=\"login_check_id\" class=\"login_id_check\" readonly=\"readonly\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"height:20px; text-align:right;\"><a href=\"#\" title=\"아이디 찾기\" class=\"help_id\" style=\"text-decoration: none\">계정을 잊으셨나요?</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"div_pwd_form\" style=\"margin-top:30px; visibility: hidden;\">\r\n");
      out.write("\t\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" id=\"login_password\" placeholder=\"비밀번호 password\" class=\"login_pwd_text\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr id=\"not_account\" style=\"text-align:left;\">\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" value=\"\" id=\"login_check_pwd\" class=\"login_pwd_check\" readonly=\"readonly\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"height:20px; text-align:right;\"><a href=\"#\" title=\"비밀번호 찾기\" style=\"text-decoration: none\">비밀번호를 잊으셨나요?</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"width:310px; margin-top:30px;\">\r\n");
      out.write("\t\t\t<div style=\"float:left; margin-top:10px;\">\r\n");
      out.write("\t\t\t\t<a href=\"createaccount.jsp\" title=\"회원가입\" style=\"text-decoration: none\">회원가입</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"float:right;\">\r\n");
      out.write("\t\t\t\t<input id=\"login_check\" onclick=\"login_check();\" type=\"button\" value=\"제 출\" class=\"login_btn\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<form action=\"main.jsp\" id=\"l_action_id\"  method=\"POST\">\r\n");
      out.write("<input type=\"hidden\" value=\"\" id=\"hidden_id\" name=\"hidden_name\">\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
