/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2019-12-17 09:51:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.sql.*;

public final class watch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<link href=\"http://vjs.zencdn.net/c/video-js.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"http://vjs.zencdn.net/c/video.js\"></script>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Hantube</title>\r\n");
      out.write("<style>\r\n");
      out.write("\thtml, body {\r\n");
      out.write("\t\t\tmargin:0;\r\n");
      out.write("\t\t\theight:100%;\r\n");
      out.write("\t\t\toverflow: hidden;\r\n");
      out.write("\t\t\tfont-family:\"나눔고딕\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\timg {\r\n");
      out.write("\t\t\tmax-width:100%; max-height:100%;\r\n");
      out.write("            vertical-align:middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.maintab {\r\n");
      out.write("\t\t\t\twidth:100%; height:60px; background:#ffffff;\r\n");
      out.write("\t\t\t\tbox-shadow: 0px 2px 4px 0px #ced6e1;\r\n");
      out.write("\t\t\t\tmargin-bottom:2px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menutab {\r\n");
      out.write("\t\t\t\tborder-right:2px solid #c9cbce;\r\n");
      out.write("\t\t\t\twidth:240px; height:100%;\r\n");
      out.write("\t\t\t\tbackground:#ffffff;\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menucontents {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth:100%; height:40px;\r\n");
      out.write("\t\t\t\tline-height:40px;\r\n");
      out.write("\t\t\t\tvertical-align:middle;\r\n");
      out.write("\t\t\t\tcolor:#474747;\r\n");
      out.write("\t\t\t\tfont-weight:normal;\r\n");
      out.write("\t\t\t\tfont-size:21px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menucontents:hover {\r\n");
      out.write("\t\t\t\tbackground-color:#e5e5e5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menucontents-icon {\r\n");
      out.write("\t\t\t\twidth:30px; height:40px;\r\n");
      out.write("\t\t\t\tmargin-left:20px;\r\n");
      out.write("\t\t\t\tmargin-right:20px;\r\n");
      out.write("\t\t\t\tfloat:left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.contentstab1 {\r\n");
      out.write("\t\t\t\twidth:100%; height:auto;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.contentstab2 {\r\n");
      out.write("\t\t\t\twidth:100%; height:500px;\r\n");
      out.write("\t\t\t\tbackground:#ffffff;\r\n");
      out.write("\t\t\t\tbox-shadow: 0px 2px 0px 0px #ced6e1;\r\n");
      out.write("\t\t\t\tmargin-bottom:2px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.contentstag {\r\n");
      out.write("\t\t\t\tdisplay: inline-block;\r\n");
      out.write("\t\t\t\twidth:50%;\r\n");
      out.write("\t\t\t\tpadding-top: 20px; padding-bottom:20px; text-align:left;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tfont-size: 18px;\r\n");
      out.write("\t\t\t\tcolor: #595959;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.videobox {\r\n");
      out.write("\t\t\t\twidth:50%; height: 100%;\r\n");
      out.write("\t\t\t\tborder:1px solid #c9cbce;\r\n");
      out.write("\t\t\t\tborder-radius:3px;\r\n");
      out.write("\t\t\t\tbackground: white;\r\n");
      out.write("\t\t\t\tmargin: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.contentsproduct {\r\n");
      out.write("\t\t\t\twidth:270px; height: 410px;\r\n");
      out.write("\t\t\t\tbackground:white;\r\n");
      out.write("\t\t\t\tmargin-left: 15px; margin-right: 15px;\r\n");
      out.write("\t\t\t\tdisplay: inline-block;\r\n");
      out.write("\t\t\t\tborder: 1px solid #c9cbce;\r\n");
      out.write("\t\t\t\tborder-radius: 3px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.logobox {\r\n");
      out.write("\t\t\t\twidth:240px; height:100%;\r\n");
      out.write("\t\t\t\tcolor:skyblue;\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tinput::-webkit-input-placeholder { text-align:left; }\r\n");
      out.write("\tinput::-moz-placeholder { text-align:left; }\r\n");
      out.write("\tinput:-ms-input-placeholder { text-align:left; }\r\n");
      out.write("\tinput:-moz-placeholder { text-align:left; }\r\n");
      out.write("\tinput::placeholder { text-align:left; }\r\n");
      out.write("\t\r\n");
      out.write("\t.searchbox {\r\n");
      out.write("\t\t\t\twidth:400px; height:100%;\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.accountbox {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth:220px; height:100%;\r\n");
      out.write("\t\t\t\tline-height:60px;x\r\n");
      out.write("\t\t\t\tvertical-align:middle;\r\n");
      out.write("\t\t\t\tfloat: right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.accountmenubox {\r\n");
      out.write("\t\t\t\twidth:320px; height:100%;\r\n");
      out.write("\t\t\t\tfloat: right;\r\n");
      out.write("\t\t\t\tline-height:60px;\r\n");
      out.write("\t\t\t\tvertical-align:middle;\r\n");
      out.write("\t\t\t\ttext-align:center;\r\n");
      out.write("\t\t\t\tfont-size: 14pt;\r\n");
      out.write("\t\t\t\tcolor: #434343;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.accountmenucontents {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth:80px; height: 100%;\r\n");
      out.write("\t\t\t\tfloat: right; vertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.accountmenucontents:hover {\r\n");
      out.write("\t\t\t\tcolor: #4c8fff;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.logocontents {\r\n");
      out.write("\t\t\t\tpadding-left: 20px; padding-top: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.searchcontents {\r\n");
      out.write("\t\t\t\tposition:relative;\r\n");
      out.write("\t\t\t\ttop:10px;\r\n");
      out.write("\t\t\t\twidth:340px; height:35px;\r\n");
      out.write("\t\t\t\tborder:1px solid #0068ff;\t\r\n");
      out.write("\t\t\t\tborder-radius:45px;\r\n");
      out.write("\t\t\t\tline-height: 35px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput:focus { outline: none;  }\r\n");
      out.write("\t\r\n");
      out.write("\t.accountcontents {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth:100px; height:42px;\r\n");
      out.write("\t\t\t\tline-height: 42px;\r\n");
      out.write("\t\t\t\tborder:1.3px solid #095bb7;\r\n");
      out.write("\t\t\t\tcolor:#0046af;\r\n");
      out.write("\t\t\t\tborder-radius:3px;\r\n");
      out.write("\t\t\t\tmargin-left: 10px;\r\n");
      out.write("\t\t\t\tmargin-right: 40px;\r\n");
      out.write("\t\t\t\tmargin-top: 6px;\r\n");
      out.write("\t\t\t\tbackground-color:white;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t\t\t\tfont-size:18px;\r\n");
      out.write("\t\t\t\tfloat:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.accountcontents img {\r\n");
      out.write("\t\t\t\tdisplay: inline;\r\n");
      out.write("\t}\r\n");
      out.write("\t.accountcontents img.over {\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.accountcontents:hover img {\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.accountcontents:hover img.over {\r\n");
      out.write("\t\t\t\tdisplay: inline;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.accountcontents:hover {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth:100px; height:42px;\r\n");
      out.write("\t\t\t\tline-height: 42px;\r\n");
      out.write("\t\t\t\tborder:1px solid #095bb7;\r\n");
      out.write("\t\t\t\tcolor:#ffffff;\r\n");
      out.write("\t\t\t\tborder-radius:3px;\r\n");
      out.write("\t\t\t\tmargin-left: 10px;\r\n");
      out.write("\t\t\t\tmargin-right: 40px;\r\n");
      out.write("\t\t\t\tmargin-top: 6px;\r\n");
      out.write("\t\t\t\tbackground-color:#095bb7;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t\t\t\tfont-size:18px;\r\n");
      out.write("\t\t\t\tfloat:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.videotitle {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px;\r\n");
      out.write("\t\t\t\tfont-size:16px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.videocomment {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px;\r\n");
      out.write("\t\t\t\tfont-size:15px;\r\n");
      out.write("\t\t\t\tcolor:#525252;\r\n");
      out.write("\t\t\t\tmargin-top:3px;\r\n");
      out.write("\t\t\t\tmargin-bottom: 7px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.videodate {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 20px;\r\n");
      out.write("\t\t\t\tline-height:20px;\r\n");
      out.write("\t\t\t\tfont-size:14px;\r\n");
      out.write("\t\t\t\tcolor:#767676;\r\n");
      out.write("\t\t\t\tvertical-align:middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.videouser {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px;\r\n");
      out.write("\t\t\t\tfont-size:15px;\r\n");
      out.write("\t\t\t\tcolor:black;\r\n");
      out.write("\t\t\t\tline-height:50px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.watchbox {\r\n");
      out.write("\t\t\t\tbackground:white; width: 960px;\r\n");
      out.write("\t\t\t\theight: 100%; margin: auto;\r\n");
      out.write("\t\t\t\tpadding:20px; margin-top: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.watchtitle {\r\n");
      out.write("\t\t\t\twidth:100%; height:30px;\r\n");
      out.write("\t\t\t\tmargin-bottom: 20px; font-size:18px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.watchcomment {\r\n");
      out.write("\t\t\t\twidth: 100%; height: auto;\r\n");
      out.write("\t\t\t\tcolor:#525252; font-size:16px;\r\n");
      out.write("\t\t\t\tmargin-top: 20px; margin-bottom: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.watchdate {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 20px; color: #767676;\r\n");
      out.write("\t\t\t\tfont-size:14px; line-height: 20px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.watchview {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 20px; color: #767676; font-size:14px;\r\n");
      out.write("\t\t\t\tline-height: 20px; vertical-align: middle; margin-bottom: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.watchthumbs-no {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 70px; height: 30px; color: #767676; font-size:14px;\r\n");
      out.write("\t\t\t\tline-height: 30px; vertical-align: middle; margin-bottom: 20px;\r\n");
      out.write("\t\t\t\ttext-align : center;\r\n");
      out.write("\t\t\t\tborder-radius: 3px;\r\n");
      out.write("\t\t\t\tcolor: white;\r\n");
      out.write("\t\t\t\tbackground: gray;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.watchthumbs-yes {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 70px; height: 30px; color: #767676; font-size:14px;\r\n");
      out.write("\t\t\t\tline-height: 30px; vertical-align: middle; margin-bottom: 20px;\r\n");
      out.write("\t\t\t\ttext-align : center;\r\n");
      out.write("\t\t\t\tborder-radius: 3px;\r\n");
      out.write("\t\t\t\tcolor: red;\r\n");
      out.write("\t\t\t\tborder:1px solid red;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.thumbsbtn {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.watchuserbox {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 60px; line-height: 40px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t\t\t\tborder-bottom:1px solid #c9cbce;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.watchuserimg {\r\n");
      out.write("\t\t\t\tfloat:left; width: 30px; height: 30px; border-radius: 50%; border:1.9px solid #cfd1d4;\r\n");
      out.write("\t\t\t\tbackground-repeat: no-repeat; background-size: 30px 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.comment_btn {\r\n");
      out.write("\t\t\t\twidth:80px; height:40px;\r\n");
      out.write("\t\t\t\tmargin-top: 10px;\r\n");
      out.write("\t\t\t\tbackground-color:#0068ff;\r\n");
      out.write("\t\t\t\tborder:0px;\r\n");
      out.write("\t\t\t\tborder-radius: 2px;\r\n");
      out.write("\t\t\t\tcolor:white;\r\n");
      out.write("\t\t\t\tfloat: right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.watchcommentlist {\r\n");
      out.write("\t\t\t\twidth: 100%; height:auto;\r\n");
      out.write("\t\t\t\tmargin-top: 50px;\r\n");
      out.write("\t\t\t\tborder-top:1px solid #c9cbce;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.threadcomment {\r\n");
      out.write("\t\t\t\twidth:100%; height:auto; margin-top: 10px;\r\n");
      out.write("\t\t\t\tcolor:#525252; font-size:16px;\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.threaddate {\r\n");
      out.write("\t\t\t\twidth:100%; height:30px; margin-top: 10px;\r\n");
      out.write("\t\t\t\tcolor: #767676; font-size:14px; \r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.accountdropmenubox {\r\n");
      out.write("\t\t\t\twidth: 160px; height: 100px; background: white;\r\n");
      out.write("\t\t\t\tposition: absolute; text-align:center;\r\n");
      out.write("\t\t\t\tborder:1px solid #c9cbce;\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t\t\t\tfont-size:18px;\r\n");
      out.write("\t\t\t\tcolor: #595959;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenureplace {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tline-height: 50px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenureplace:hover {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tbackground: #e5e5e5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenulogout {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tline-height: 50px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenulogout:hover {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tbackground: #e5e5e5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.insertdropmenubox {\r\n");
      out.write("\t\t\t\twidth: 160px; height: 150px; background: white;\r\n");
      out.write("\t\t\t\tposition: absolute; text-align:center;\r\n");
      out.write("\t\t\t\tborder:1px solid #c9cbce;\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t\t\t\tfont-size:18px;\r\n");
      out.write("\t\t\t\tcolor: #595959;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenuvideo {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tline-height: 50px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenuvideo:hover {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tbackground: #e5e5e5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenureview {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tline-height: 50px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenureview:hover {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tbackground: #e5e5e5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenupost {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tline-height: 50px;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropmenupost:hover {\r\n");
      out.write("\t\t\t\twidth: 100%; height: 50px; float: left;\r\n");
      out.write("\t\t\t\tbackground: #e5e5e5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropvideobox {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 60px; height: 30px; color: #767676; font-size:14px;\r\n");
      out.write("\t\t\t\tline-height: 30px; vertical-align: middle; margin-bottom: 0px;\r\n");
      out.write("\t\t\t\ttext-align : center;\r\n");
      out.write("\t\t\t\tborder-radius: 3px;\r\n");
      out.write("\t\t\t\tcolor: #0068ff;\r\n");
      out.write("\t\t\t\tfloat: right;\r\n");
      out.write("\t\t\t\tborder: 1px solid #0068ff;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropvideobox:hover {\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\twidth: 60px; height: 30px; color: #767676; font-size:14px;\r\n");
      out.write("\t\t\t\tline-height: 30px; vertical-align: middle; margin-bottom: 0px;\r\n");
      out.write("\t\t\t\ttext-align : center;\r\n");
      out.write("\t\t\t\tborder-radius: 3px;\r\n");
      out.write("\t\t\t\tcolor: white;\r\n");
      out.write("\t\t\t\tbackground:#0068ff;\r\n");
      out.write("\t\t\t\tfloat: right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction accountdropmenu() {\r\n");
      out.write("\t\tif(document.getElementById('account_checkdropmenustate').value == 1){\r\n");
      out.write("\t\t\t$(\".accountdropmenubox\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\tdocument.getElementById('account_checkdropmenustate').value = 2;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\".accountdropmenubox\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\tdocument.getElementById('account_checkdropmenustate').value = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction insertdropmenu() {\r\n");
      out.write("\t\tif(document.getElementById('insert_checkdropmenustate').value == 1){\r\n");
      out.write("\t\t\t$(\".insertdropmenubox\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\tdocument.getElementById('insert_checkdropmenustate').value = 2;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\".insertdropmenubox\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\tdocument.getElementById('insert_checkdropmenustate').value = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction delete_contents() {\r\n");
      out.write("\t\t$idhidden = document.getElementById('videoidhidden').value;\r\n");
      out.write("\t\tif(confirm(\"정말로 삭제하시겠습니까?\")){\r\n");
      out.write("\t\t\tlocation.href='./deleteaction.jsp?videoid='+$idhidden;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String idv = request.getParameter("hidden_name");
	String videoid = request.getParameter("video");
	
	
	
	if(videoid == null){
		response.sendRedirect("main.jsp");
	}
	if(idv != null){
		session.setAttribute("id_login", idv);
	}
	String id_login = (String)session.getAttribute("id_login");

	String login_nick = "";
	String login_img = "";

	String login_state_yes = "display:none;";
	String login_state_no = "display:none;";
	
	String comment_login_state = "";
	String comment_login_state_btn = "";

      out.write('\r');
      out.write('\n');

Connection conn=null;
PreparedStatement pstmt = null;
ResultSet rs = null;


try{
	String driverName = "com.mysql.cj.jdbc.Driver";
	String jdbcUrl = "jdbc:mysql://localhost:3306/han_db?serverTimezone=Asia/Seoul";
	String dbId="guestid2019";
	String dbPass="guestpwd2019";
	
	Class.forName("com.mysql.cj.jdbc.Driver");
	conn = DriverManager.getConnection(jdbcUrl, dbId, dbPass);

	if(id_login != null){
		String sql = "select * from account_db where user_id = '" + id_login + "'";
		pstmt = conn.prepareStatement(sql);
		rs = pstmt.executeQuery();
		if(rs.next()){
			login_nick = rs.getString("user_nick");
			login_img = rs.getString("user_img");
		}
		
	}
	
}catch(Exception e){
	e.printStackTrace();
}finally{
	if(conn != null)
		try{conn.close();}catch(SQLException sqle){}
	if(pstmt != null)
		try{conn.close();}catch(SQLException sqle){}
	if(rs != null)
		try{conn.close();}catch(SQLException sqle){}
}

      out.write('\r');
      out.write('\n');

	if(id_login != null){
		login_state_yes = "display:block;";
		login_state_no = "display:none;";
		comment_login_state = "placeholder='댓글을 작성하세요.'";
		comment_login_state_btn = "display:yes;";
	}else{
		login_state_yes = "display:none;";
		login_state_no = "display:block;";
		comment_login_state = "placeholder='로그인 후 작성이 가능합니다.' readonly='readonly'";
		comment_login_state_btn = "display:none;";
	}



      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"maintab\">\r\n");
      out.write("\t<div class=\"logobox\">\r\n");
      out.write("\t\t<div class=\"logocontents\">\r\n");
      out.write("\t\t\t<img src=\"resources/imgs/hantv.png\" OnClick=\"location.href='main.jsp'\" style=\"cursor:pointer;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"searchbox\">\r\n");
      out.write("\t\t<div class=\"searchcontents\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-left:10px;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><img src=\"resources/imgs/search_btn.png\"></a>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"검색\" style=\"width:290px; border:none;\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"accountbox\" style=\"");
      out.print(login_state_no);
      out.write("\">\r\n");
      out.write("\t\t<div class=\"accountcontents\" OnClick=\"location.href='login.jsp'\">\r\n");
      out.write("\t\t\t<div style=\"margin-left:10px;\">\r\n");
      out.write("\t\t\t\t로그인\r\n");
      out.write("\t\t\t\t<img src=\"resources/imgs/login_btn.png\">\r\n");
      out.write("\t\t\t\t<img src=\"resources/imgs/login_btn_rollover.png\" class=\"over\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"accountbox\" style=\"");
      out.print(login_state_yes);
      out.write("\" onclick=\"accountdropmenu();\">\r\n");
      out.write("\t\t<div style=\"border-left:1px solid #dcdddf; width:100px; height:100%; padding-left:20px; float: left; text-align: right;\">\r\n");
      out.write("\t\t\t");
      out.print(login_nick );
      out.write("\r\n");
      out.write("\t\t\t<div class=\"accountdropmenubox\">\r\n");
      out.write("\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"account_checkdropmenustate\" value=\"1\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropmenureplace\" OnClick=\"location.href='#'\">\r\n");
      out.write("\t\t\t\t\t\t계정수정\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropmenulogout\" OnClick=\"location.href='logout.jsp'\">\r\n");
      out.write("\t\t\t\t\t\t로그아웃\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"width:40px; height:40px; margin-right:40px; float: right;\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(login_img);
      out.write("\" style=\"width:40px; height:40px;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"accountmenubox\" style=\"");
      out.print(login_state_yes);
      out.write("\">\r\n");
      out.write("\t\t<div class=\"accountmenucontents\" style=\"margin-left: 10px; margin-right: 20px;\">\r\n");
      out.write("\t\t내채널\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"accountmenucontents\" style=\"margin-right: 10px;\" onclick=\"insertdropmenu();\">\r\n");
      out.write("\t\t올리기\r\n");
      out.write("\t\t\t<div class=\"insertdropmenubox\">\r\n");
      out.write("\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"insert_checkdropmenustate\" value=\"1\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropmenuvideo\" OnClick=\"location.href='uploadvideo.jsp'\">\r\n");
      out.write("\t\t\t\t\t\t동영상\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropmenureview\" OnClick=\"location.href='review.jsp'\">\r\n");
      out.write("\t\t\t\t\t\t동영상 리뷰\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropmenupost\" OnClick=\"location.href='uploadpost.jsp'\">\r\n");
      out.write("\t\t\t\t\t\t게시글\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"menutab\">\r\n");
      out.write("\t<div style=\"width:100%; height:10px;\">\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"menucontents\" OnClick=\"location.href='main.jsp'\">\r\n");
      out.write("\t\t<div class=\"menucontents-icon\">\r\n");
      out.write("\t\t\t<img src=\"resources/imgs/home_normal.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"float:left;\">\r\n");
      out.write("\t\t\t홈\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"menucontents\" OnClick=\"location.href='video.jsp'\">\r\n");
      out.write("\t\t<div class=\"menucontents-icon\">\r\n");
      out.write("\t\t\t<img src=\"resources/imgs/hot_normal.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"float:left;\">\r\n");
      out.write("\t\t\t동영상\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"menucontents\" OnClick=\"location.href='review.jsp'\">\r\n");
      out.write("\t\t<div class=\"menucontents-icon\">\r\n");
      out.write("\t\t\t<img src=\"resources/imgs/review_normal.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"float:left;\">\r\n");
      out.write("\t\t\t동영상 리뷰\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"menucontents\" OnClick=\"location.href='board.jsp'\">\r\n");
      out.write("\t\t<div class=\"menucontents-icon\">\r\n");
      out.write("\t\t\t<img src=\"resources/imgs/text_normal.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"float:left;\">\r\n");
      out.write("\t\t\t게시글\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");

conn=null;
pstmt = null;
rs = null;

String videoTitle = "";
String videoUser = "";
String videoDate = "";
String videoComment = "";
String videoSrc = "";
int videoView = 0;
int videoThumbs = 0;

String VMnick = "";
String VMimgSrc = "";

String thumbsCheck = "";

String dropCheck = "";


try{
	String driverName = "com.mysql.cj.jdbc.Driver";
	String jdbcUrl = "jdbc:mysql://localhost:3306/han_db?serverTimezone=Asia/Seoul";
	String dbId="guestid2019";
	String dbPass="guestpwd2019";
	
	Class.forName("com.mysql.cj.jdbc.Driver");
	conn = DriverManager.getConnection(jdbcUrl, dbId, dbPass);

	String sql = "select * from video_db where cid = '" + videoid + "'";
	pstmt = conn.prepareStatement(sql);
	rs = pstmt.executeQuery();

	if(rs.next()){
		videoTitle = rs.getString("vtitle");
		videoUser = rs.getString("userid");
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy년 MM월 dd일 hh:mm:ss");
		videoDate = sdf.format(rs.getTimestamp("signdate"));
		videoComment = rs.getString("comment");
		videoSrc = rs.getString("videoname");
		videoView = rs.getInt("viewcnt");
		videoThumbs = rs.getInt("thumbscnt");
		
		sql = "update video_db set viewcnt = viewcnt+1 where cid = '"+videoid+"'";
		pstmt = conn.prepareStatement(sql);	// 쿼리문 수행할 객체 생성
		pstmt.executeUpdate();
	}else{
		out.print("비디오 불러오지 못함");
	}
	
	sql = "select * from account_db where user_id = '"+videoUser+"'";
	pstmt = conn.prepareStatement(sql);
	rs = pstmt.executeQuery();
	
	if(rs.next()){
		VMnick = rs.getString("user_nick");
		VMimgSrc = rs.getString("user_img");
		
		
		if(videoUser.equals(id_login)){
			dropCheck = "style='display:block;'";
		}else{
			dropCheck = "style='display:none;'";
		}
		
	}else{
		out.print("계정 불러오지 못함");
	}
	
	sql = "select userid from thumbs_db where videocid = '"+videoid+"' && userid = '"+id_login+"'";
	pstmt = conn.prepareStatement(sql);
	rs = pstmt.executeQuery();
	
	if(rs.next()){
		thumbsCheck = "watchthumbs-yes";
	}else{
		thumbsCheck = "watchthumbs-no";
	}
	
}catch(Exception e){
	e.printStackTrace();
}finally{
	if(conn != null)
		try{conn.close();}catch(SQLException sqle){}
	if(pstmt != null)
		try{conn.close();}catch(SQLException sqle){}
	if(rs != null)
		try{conn.close();}catch(SQLException sqle){}
}

      out.write("\r\n");
      out.write("<div style=\"overflow: auto; width:100%-240px; height:100%; background: #f2f4f7;\">\r\n");
      out.write("\t<div class=\"watchbox\">\r\n");
      out.write("\t\t<div class=\"watchtitle\">\r\n");
      out.write("\t\t\t");
      out.print(videoTitle );
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"width:100%; height: 540px;\">\r\n");
      out.write("\t\t<video src=\"./resources/contents/videos/");
      out.print(videoSrc );
      out.write("\" controls=\"controls\" class=\"video-js vjs-default-skin\" style=\"width:100%; height:100%; float:left; border:0px;\" type=\"video/mp4\">\r\n");
      out.write("\t\t</video>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"watchcomment\">\r\n");
      out.write("\t\t \t");
      out.print(videoComment );
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"watchdate\">\r\n");
      out.write("\t\t\t");
      out.print(videoDate );
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"dropvideobox\" ");
      out.print(dropCheck );
      out.write(" onclick=\"delete_contents();\">\r\n");
      out.write("\t\t\t삭 제\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"watchview\">\r\n");
      out.write("\t\t\t조회수 ");
      out.print(videoView );
      out.write("회 ㆍ 좋아요 ");
      out.print(videoThumbs );
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"");
      out.print(thumbsCheck);
      out.write("\" OnClick=\"location.href='thumbsaction.jsp?userid=");
      out.print(id_login);
      out.write("&cid=");
      out.print(videoid);
      out.write("'\" style=\"");
      out.print(comment_login_state_btn);
      out.write("\"\">\r\n");
      out.write("\t\t\t좋아요\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"watchuserbox\">\r\n");
      out.write("\t\t\t<div class=\"watchuserimg\" style=\"background-image: url('");
      out.print(VMimgSrc );
      out.write("');\">\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"margin-left: 10px; float: left;\">\r\n");
      out.write("\t\t\t\t");
      out.print( VMnick );
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"commentaction.jsp\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"CMtext\" ");
      out.print(comment_login_state );
      out.write(" style=\"width: 85%; height: 50px; margin-left: 30px; border: 0px;\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"제출\" class=\"comment_btn\" style=\"");
      out.print(comment_login_state_btn);
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"videoidhidden\" name=\"videoid\" value=\"");
      out.print(videoid);
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"CMid\" value=\"");
      out.print(id_login);
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"CMnick\" value=\"");
      out.print(login_nick);
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"CMimgsrc\" value=\"");
      out.print(login_img);
      out.write("\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"watchcommentlist\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");

conn=null;
pstmt = null;
rs = null;

try{
	String driverName = "com.mysql.cj.jdbc.Driver";
	String jdbcUrl = "jdbc:mysql://localhost:3306/han_db?serverTimezone=Asia/Seoul";
	String dbId="guestid2019";
	String dbPass="guestpwd2019";
	
	Class.forName("com.mysql.cj.jdbc.Driver");
	conn = DriverManager.getConnection(jdbcUrl, dbId, dbPass);

	String sql = "select * from comment_db where videocid = '" + videoid + "' order by signdate desc";
	pstmt = conn.prepareStatement(sql);
	rs = pstmt.executeQuery();
	while(rs.next()){
		String CMnick = rs.getString("usernick");
		String CMimgsrc = rs.getString("userimg");
		String CMcomment = rs.getString("comment");
		
      out.write("\r\n");
      out.write("\t\t<div style=\"width: 960px; height: 200px; margin:auto; background: white; padding-left: 20px; padding-right: 20px;\">\r\n");
      out.write("\t\t\t<div style=\"width: 100%; height: 40px;\">\r\n");
      out.write("\t\t\t\t<div class=\"watchuserimg\" style=\"background-image: url('");
      out.print(CMimgsrc );
      out.write("');\">\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"margin-left: 10px; float: left; line-height: 40px; vertical-align: bottom;\">\r\n");
      out.write("\t\t\t\t\t");
      out.print( CMnick);
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"threadcomment\">\r\n");
      out.write("\t\t\t\t\t");
      out.print( CMcomment);
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"threaddate\">\r\n");
      out.write("\t\t\t\t\t");

					SimpleDateFormat sdf = new SimpleDateFormat("yyyy년 MM월 dd일 hh:mm:ss");
					String CMvideoDate = sdf.format(rs.getTimestamp("signdate"));
					out.println(CMvideoDate);
					
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
	
	}
}catch(Exception e){
	e.printStackTrace();
}finally{
	if(conn != null)
		try{conn.close();}catch(SQLException sqle){}
	if(pstmt != null)
		try{conn.close();}catch(SQLException sqle){}
	if(rs != null)
		try{conn.close();}catch(SQLException sqle){}
}

      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
